### ISSUE TITLE
Error reading 'o' stream in .frx data: expected cbMorphData

### ISSUE THREAD

**Issue by fasen** [chelh/VBASync#10]
When opening one specific project folder I get this error message:

> Error reading 'o' stream in .frx data: expected cbMorphData size 24, but actual size was 28.

See also[ MorphDataControl.cs](https://github.com/chelh/VBASync/blob/41f510e509274ffcd14a22ccb418a0e2f007be10/src/VBASync.Model/FrxObjects/MorphDataControl.cs#L68)

Other project folders with .frx files work just fine. 

Edit: This is on version 1.1.4

**Comment by chelh** [comment]
Could you please attach a file that's giving you trouble? There's not much I can do without that.

**Comment by fasen** [comment]
I can reproduce the error with any file:
* I have a user form with a list box element
* I change the property "SpecialEffect" of that list box to "0 - fmSpecialEffectFlat" (or anything else but "2 - fmSpecialeffectSunken")
* I save and close the file 
* I start VBASync (passing the .ini file via target in a shorcut), apply the changes to my folder and quit VBASync
* I start VBASync (passing the .ini file via target in a shorcut) and get the error

So I assume the error is caused by the property "SpecialEffect" of a list box element. As long as it is set to "2 - fmSpecialeffectSunken" everything is fine.

**Comment by chelh** [comment]
I've checked in a change to fix this and a similar issue with label controls. Could you please check that this new build works as expected?

[VBA.Sync.Tool-v1.1.6.zip](https://github.com/chelh/VBASync/files/855015/VBA.Sync.Tool-v1.1.6.zip)

**Comment by fasen** [comment]
Works like a charm. Thanks.
