### ISSUE TITLE
Options not saved

### ISSUE THREAD

**Issue by hectorticoli** [chelh/VBASync#11]
Hello,

Tested on version 1.1.6b (and 1.1.4), if I specify a diff tool and close VBASync, then the options are empty again when I start VBASync again.

**Comment by chelh** [comment]
Yeah, I've been noticing this too. In version 1.2.0 I'm moving `LastSession.ini` from isolated storage into `%AppData%`, and that will almost certainly fix it.

**Comment by hectorticoli** [comment]
Okay. I would separate Settings saving from Session saving (as diff tool definition is not really related to the file and folder you're working on). How about introducing a Settings.ini file (as you probably have all the code to parse a ini file)?

**Comment by chelh** [comment]
VBASync has never loaded the file and folder settings from `LastSession.ini`, except when the user signals that they want this (via **File**→**Load last session**). So session and settings persistence is already separate, even if they are in the same file.

**Comment by hectorticoli** [comment]
Okay :-)

**Comment by chelh** [comment]
Fixed in release 1.2.0
