### ISSUE TITLE
Improvement: LastSession.ini in Application folder for Portable version

### ISSUE THREAD

**Issue by hectorticoli** [chelh/VBASync#12]
Hello chelh,

Thanks for the portable version of 1.2.0. The version even solved another issue I didn't have time to report. I would ask for an extra improvement for the portable version, so that it really becomes a portable version (without extra data outside the current application folder).

Let me know if this can be done without too much troubles.

**Comment by hectorticoli** [comment]
I saw that you introduced the "Portable=True" with VBASync.ini in version 1.3.0 RC. I noticed that even with this option, if a LastSession.ini file exists in %appdata%, options are not displayed on first launch (so the application isn't entirely standalone in this case). You're close to the point!

**Comment by chelh** [comment]
Here's an updated RC. Thanks for testing! [Portable VBA Sync Tool 1.3.0.zip](https://github.com/chelh/VBASync/files/904059/Portable.VBA.Sync.Tool.1.3.0.zip)

**Comment by hectorticoli** [comment]
This updated version seems okay about the Portable setting.

**Comment by chelh** [comment]
[VBA Sync Tool 1.3.0 is now released!](https://github.com/chelh/VBASync/releases/latest)
