### ISSUE TITLE
Improvement: List of recently stored sessions

### ISSUE THREAD

**Issue by hectorticoli** [chelh/VBASync#13]
Another idea for improvement:
That would be even more user friendly to have access of recently stored sessions from the "File" menu (5 last stored sessions for example).

I'm pretty sure there is a workaround using the new command line options of 1.2.0 and windows shortcuts, but I will surely take advantage of that new feature.

Thanks!

**Comment by chelh** [comment]
Please try out this release candidate and get back to me: [Portable VBA Sync Tool 1.3.0.zip](https://github.com/chelh/VBASync/files/902841/Portable.VBA.Sync.Tool.1.3.0.zip)

**Comment by hectorticoli** [comment]
I'll test this version tomorrow about the recent item list.

**Comment by hectorticoli** [comment]
The recent list item appears, but I'm not sure I tested to recall a recent session. Last thing before the release, I would move the "Settings" menu item above the recent session list (just to keep this list almost at the bottom).

**Comment by hectorticoli** [comment]
Rearranged recent file list OK, and recall a recent session works too. Didn't try the case of a deleted session file, but that's not mandatory for the very next version (maybe you already managed the case though).

**Comment by chelh** [comment]
[VBA Sync Tool 1.3.0 is now released!](https://github.com/chelh/VBASync/releases/latest)
