### ISSUE TITLE
If merge tool path is given between quotes in settings, then the tool can't be used

### ISSUE THREAD

**Issue by hectorticoli** [chelh/VBASync#16]
Hello,

I noticed that the merge tool works only if the path is not given between quotes. I copied/pasted the path from a shortcut, and I've just found out today what the problem was.

Identified in 1.3.0 RC (don't remember which one)

**Comment by chelh** [comment]
A fix will be included with the next release. I wasn't aware that it was standard behavior to strip quotes from user-supplied paths like that, thanks!

**Comment by hectorticoli** [comment]
Well, I don't know if that's a standard. That's just that I copied/pasted without wondering about the quote. There was spaces in the path, so I kept quotes "just to be sure". 
Thanks for the fix^^
