### ISSUE TITLE
Linux-compatible command-line version

### ISSUE THREAD

**Issue by chelh** [chelh/VBASync#17]
Please comment or emote here if you'd like me to find some way to get VBA Sync Tool working as a command-line executable under Linux, in addition to the normal Windows GUI. I've tried a couple of approaches already, and would like to gauge the actual level of interest in this before pursuing it further.

**Comment by hectorticoli** [comment]
I'm only working with Windows for Office files with VBA. I thought automation on Office files wasn't available on Linux, but maybe that was just some time ago. 
So to me, that would be low priority.

**Comment by chelh** [comment]
Most VBA source control tools use Office's own APIs for dealing with Office files. That's the easy way to do it, but it introduces a hard dependency on Office.

VBA Sync Tool is different because it's a pure .Net solution using the OpenMCDF library, no Office APIs needed! That means that it's quite feasible to make a Linux version; it's just a matter of getting the actual program logic separated completely from the WPF API I'm using for my GUI.

**Comment by chelh** [comment]
As of version 2.0.0 the tool runs under Linux, but only if all settings are specified on the command-line, including auto-run. I'll consider this good enough for now.
