### ISSUE TITLE
WPF GUI sometimes doesn't obey cherry-picking

### ISSUE THREAD

**Issue by princekream** [chelh/VBASync#18]
Hi there,

So the good news is v.2.0 kicks a**!  It's publishes and extract's VBA to the SVN.

However, since v2.0 I noticed that publishing will something delete VBA script from the SVN, even though I've cleared deselected that I didn't want files deleted.  Same for extracting, files will disappear from the SVN randomly.  Not sure if it's settings (checkbox) not being propagated, or mismatch on matching up the SVN files to the ones on the Excel/Office file.

Let me know if you need me to run some test cases :)

Thanks again for this great tool, I'm contemplating installing VS to help debug/code!

**Comment by chelh** [comment]
Are you using the portable version, or the installer?

**Comment by chelh** [comment]
Also, if you were using the **OK** button previously, I'd like you to start using the **Apply** button instead, and note the program's behavior. Do the unselected deletions disappear from the changes list when they're executed? Do their checkboxes tick immediately before they're executed?

**Comment by princekream** [comment]
Hi again,

Small update.  I think I figured it out and it's not related to VBASync :+1: 

The "disappearing" files syndrome is due to my encrypted drive.  My encryption is kicking in before VBAsync has had the time to fully dump the VBA file I'm extracting.  It starts encrypting a semi-complete file and creates a corrupted table of contents on the encryption-side... and then, the VBA file disappears as it can't be decrypted successfully.

All in all, my fault on this one.  Sorry!

Answers to previous questions: I'm using the portable version and am always using Apply instead of OK - as OK closes the window and I have more work to do :)

Thanks!
