### ISSUE TITLE
Refresh synchronization after Extract or Publish

### ISSUE THREAD

**Issue by hectorticoli** [chelh/VBASync#19]
Hi chelh,

I saw a few issues about publish problems (already fixed). If after an extract or publish, you refresh the list - not as it "should be", but using the standard refresh - without selecting any item, I think you'll get the same result in most cases, but if some new extract/publish issue appears, then the user will see that as an extract or publish problem.

What do you think?

**Comment by chelh** [comment]
Fixed in release 2.0.1, thanks!
