### ISSUE TITLE
Allow drag and drop of folder and file

### ISSUE THREAD

**Issue by hectorticoli** [chelh/VBASync#20]
Hi chelh,

Could you add the possibility to set office file and VBA Folder using drag and drop from explorer ?

Thanks

**Comment by hectorticoli** [comment]
Tested on version 2.0.2. It works. If that's not too much troubles, I would prevent to drop folders as Office file, or file as Source folder.

Thanks!

**Comment by chelh** [comment]
Yes, in a recent change I've made it so that if you drop in a file as a folder and a folder as a file, the tool will automatically switch their places.

**Comment by hectorticoli** [comment]
Okay, I'll wait for the next version to test it then :-)

**Comment by hectorticoli** [comment]
Version 2.1.2 is OK about this issue. 

> Yes, in a recent change I've made it so that if you drop in a file as a folder and a folder as a file, the tool will automatically switch their places.

I haven't be able to reproduce that, but with field validation, that's not a problem anymore.
