### ISSUE TITLE
Recent files are ignored if specified as relative path

### ISSUE THREAD

**Issue by hectorticoli** [chelh/VBASync#22]
Hi chelh, 

If recent files are specified as relative path in Lastsession.ini, they are not loaded.

Tested in version 2.0.1

**Comment by chelh** [comment]
Sorry about that. Could you please try this most recent build to see that it solves the problem?

[Portable VBA Sync Tool 2.0.2.zip](https://github.com/chelh/VBASync/files/963465/Portable.VBA.Sync.Tool.2.0.2.zip)

**Comment by chelh** [comment]
Sorry about that. Please try this most recent build, which should fix it. Disregard the previous version I sent.

[Portable VBA Sync Tool 2.0.2.zip](https://github.com/chelh/VBASync/files/963481/Portable.VBA.Sync.Tool.2.0.2.zip)

**Comment by chelh** [comment]
BTW, could you please translate these two strings?

 * “FRX file difference” (appears as a title bar)
 * “Cannot load WPF UI. If your system is non-Windows or otherwise doesn't support WPF, you may only run VBA Sync Tool by specifying -r on the command-line.” (error message)

**Comment by hectorticoli** [comment]
The first field was already translated. About the second field, what does the "-r" argument do? Do you have another GUI, or is it a flag to force VBASync to run as command-line only?
The current message isn't quite clear about that.

**Comment by hectorticoli** [comment]
Before you give me details, here is the resource file with a direct translation of the message. Maybe I'll have to change it afterwards, maybe not.
[VBASyncResources.fr.resx.txt](https://github.com/chelh/VBASync/files/966895/VBASyncResources.fr.resx.txt)
Enjoy

**Comment by hectorticoli** [comment]
By the way, it seems that your fix for this issue works. Thanks!
