### ISSUE TITLE
Differentiate extract/publish Office document

### ISSUE THREAD

**Issue by BaronBodissey** [chelh/VBASync#29]
Hi anew,

Would it be possible to differentiate the extracted and the published office document. And even a root "template" office document.

That's to say for example that we conceive the office document in a working directory c:\whatever\work\.
That the source code repo is in another directory c:\src\awesomeprojectrepo\.
And finally, as we do not want any change in the styles of the document happening during the "conceive" phase, we'd like that the publish starts from a "template" office document (note also that this document may or may not already contains the vba content).

So we'd have 3 files and 4directories
c:\whatever\work\source.doc -> the source document to extract from
c:\src\awesomeprojectrepo\bin\target.doc -> the target document to publish to
c:\src\awesomeprojectrepo\src\ -> the source/target directory to extract-to/publish-from (including the ini file)
c:\src\awesomeprojectrepo\template\template.doc -> the root template document to publish from

Thx

**Comment by chelh** [comment]
I've thought about this before, since I use VBA Sync myself to help with developing an Excel `.xla` add-in. But I don't want to complicate the UI with extra fields that many people won't use! Perhaps you could use VBA Sync's command-line interface instead:

```Batchfile
VBASync -r -x -f WorkingCopy.xls -d Repo
copy /y BaseAddIn.xla PublishedAddIn.xla
VBASync -r -p -f PublishedAddIn.xla -d Repo
```

**Comment by BaronBodissey** [comment]
I have to test that kind of process. I didn't think about it as I was still in automation mode in my reflection. And when you use automation, even if the vba files didn't changed, the generated document would be changed. And this we cannot afford.

If VBASync generates exactly the same document every time then we might have a winner ;-) .

So I going to evaluate this option...

**Comment by BaronBodissey** [comment]
Ok it seems to work properly.

Maybe you could had a non-regression test to verify that the generated office document is exactly the same when you generate twice without modifiying neither the "template" document nor the vbas.

I think I might not be the only one to have this concern.

Thx.

**Comment by chelh** [comment]
Okay, I've added that integration test for a very basic scenario. Let me know if you ever notice a scenario where publishing is non-repeatable, and I'll add another integration test to cover that case.
