### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by epieters** [chelh/VBASync#31]
I successfully installed VBA Sync and managed to get the first commit into git.
But when I try again, I'm getting an "Input string was not in correct format" error message.
Both my VBA code and the xlsm are currently under version control.

<img width="378" alt="vbasyncerror" src="https://user-images.githubusercontent.com/3625977/27526386-b4bb95c6-5a45-11e7-805c-80d54f1ca157.png">

**Comment by chelh** [comment]
Any chance you could send the file and the contents of that folder?

**Comment by chelh** [comment]
Hi, if you cannot send me the problematic file and the contents of the extracted folder, I'm afraid I'll have to close this. If you could make some other file exhibit this behavior and send me that plus *its* extracted folder, that would work too. I just need to be able to reproduce this locally within the next week or so…

**Comment by chelh** [comment]
It may also help if you try this using the very latest release candidate:

[Portable VBA Sync Tool 2.2.0.zip](https://github.com/chelh/VBASync/files/1150754/Portable.VBA.Sync.Tool.2.2.0.zip)

**Comment by epieters** [comment]
Sorry for the delay. I've installed version 2.2.0 and am able to extract the VBA from the excel file.
Only the form is not extracted
<img width="251" alt="vbasync" src="https://user-images.githubusercontent.com/3625977/29406855-a540921a-8342-11e7-8aa5-79946e76ab12.png">

**Comment by epieters** [comment]
the original bug is fixed, so closing this issue
