### ISSUE TITLE
Sequence does not contain any elements when Class name case does not match

### ISSUE THREAD

**Issue by RupertAvery** [chelh/VBASync#4]
For some reason if the BIFF file name case does not match the declared file name, the following code in VbaFolder.cs throws an exception

```
case "CLASS":
     modules.First(m => m.Name == split[1]).Type = ModuleType.Class;
```

This can be remedied by uppercasing everything, or doing a case insensitive match

**Comment by chelh** [comment]
I've just put out a [new release](https://github.com/chelh/VBASync/releases) with this bug fixed. Thanks for reporting it!
