### ISSUE TITLE
Command line extract/publish

### ISSUE THREAD

**Issue by RupertAvery** [chelh/VBASync#5]
It would be useful to have a command line version that can be run from a batch file. Extraction can ignore diffs by default as we are expecting to extract into a version-controlled folder. The publish can be like a compile step, merging the source files into a binary file.

**Comment by chelh** [comment]
Try saving a session, then adding `AutoRun = true` to the top of the session `.ini` file. Launch VBA Sync with the session file as an argument. That _should_ allow it to run without any user interaction.

See `MainWindow.xaml.cs`:216–253 for where this happens.

**Comment by chelh** [comment]
More command-line options are in release 1.2.0
