### ISSUE TITLE
Error "Object reference not set to an instance of an object" then crash if Office file is opened

### ISSUE THREAD

**Issue by hectorticoli** [chelh/VBASync#7]
Hello,

I was testing your software this evening, and found a bug (using version 1.1.4). Here is the scenario:
I created a XLSM file containing a Module, a class and a UserForm (with a button). On scenario start, the XLSM file is opened.
- Extract the VBA content to a folder
- Modify the module using a text editor
- Refresh then publish the changes (while the XLSM file is open). You get the error message
- Then, close Excel instance and click on "Refresh". The program stops.

If you're unable to reproduce the problem, I'll be able to provide my sample XLSM file.

**Comment by hectorticoli** [comment]
By the way, I tried to contact you directly without success: I had trouble to compile the project using VS2015 Community, and if you're interested with french translation, then I might be able to help.

**Comment by chelh** [comment]
I'll look into this this evening, but it may work out that the best I can do is give you a more descriptive error message.

Also, to open the solution, you will need Visual Studio 2017, although I can roll back to a Visual Studio 2015–compatible project if needed for your translation. Thanks!

**Comment by chelh** [comment]
This is fixed in [release 1.1.5](https://github.com/chelh/VBASync/releases).

Also, where did you get a link to contact me directly, so I can correct that info?

**Comment by hectorticoli** [comment]
Well, that's the point, I didn't find any link to contact you directly ^^
Do you have an existing Change Request on multi-Language management?
Do you have an idea about how you'd implement the multi-language?

**Comment by chelh** [comment]
Ah okay, I'll add a note to the main page that the best method of contacting me is to open an issue.

I've also opened issue #8 as a place to coördinate translations, and wrote some basic steps there on how to translate the project's `.resx` file.
